### ISSUE TITLE
All interactions with ClassTransformer should use modified context classloader

### ISSUE THREAD

**Issue by philipa** [icon-Systemhaus-GmbH/javassist-maven-plugin#43]
The context classloader is adjusted to add the input directory the local build output directory and the dependencies before calling the transformation methods.

I think the context classloader should be set around all interactions with the ClassTransformer. This would allow configure() to access classes in the local project, and also allow the ClassTransformer implementations to be loaded from the local project.

If you agree, I'm happy to do the work. I'd pull the context classloader management up from JavassistTransformerExecutor.execute() to JavassistMojo.execute().

**Comment by kringol** [comment]
Any update on when 1.2.0 is going to be released?

**Comment by barthel** [comment]
1.2.0 will be done around the 30th June 2015.

See. https://github.com/icon-Systemhaus-GmbH/javassist-maven-plugin/milestones
