### ISSUE TITLE
Versions dependencies conflicts

### ISSUE THREAD

**Issue by Macadoshis** [icon-Systemhaus-GmbH/javassist-maven-plugin#47]
I'm using enforcer-plugin and it detects followings version conflicts, regarding :

    <groupId>org.codehaus.plexus</groupId>
    <artifactId>plexus-utils</artifactId>

and

    <groupId>org.codehaus.plexus</groupId>
    <artifactId>plexus-classworlds</artifactId>

How come did you push a release into maven central without checking version conflicts ??

**Comment by barthel** [comment]
I'll integrate the Maven Enforcer Plugin too.

**Comment by barthel** [comment]
There is a conflict between `maven-core` and `maven-plugin-api` :-/ :
```
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.codehaus.plexus:plexus-classworlds:2.4 paths to dependency are:
+-de.icongmbh.oss.maven.plugins:javassist-maven-plugin:1.2.0-SNAPSHOT
  +-org.apache.maven:maven-plugin-api:3.2.1
    +-org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5
      +-org.codehaus.plexus:plexus-classworlds:2.4
and
+-de.icongmbh.oss.maven.plugins:javassist-maven-plugin:1.2.0-SNAPSHOT
  +-org.apache.maven:maven-core:3.2.1
    +-org.codehaus.plexus:plexus-classworlds:2.5.1
]
```
