### ISSUE TITLE
Store and stamp new generated inner/nested classes

### ISSUE THREAD

**Issue by jmarcgit** [icon-Systemhaus-GmbH/javassist-maven-plugin#48]
Hi,
I'm generating inner classes so I need to write the new classes to file.
`inner.writeFile("./target/classes");`
just works but it would be nicer to add a method  that could save the class  using the  build path and mark the new class as processed too.

I can implement the feature for you.

**Comment by barthel** [comment]
Feel free to open an PR.

Thanks for your contribution.

**Comment by jmarcgit** [comment]
Ok but it seems that the source code in the master branchy is very different from the one I'm using (1.1.0)
